sonar.projectKey=MySpringApp
sonar.projectName=My Spring App
sonar.projectVersion=1.0

# Source settings
sonar.sources=src
sonar.java.binaries=target

# Server location
sonar.host.url=http://localhost:7070

# Authentication (create a token in SonarQube UI)
sonar.token=sqa_1ca4dd1db7068ac07a5cd3832b0fca4a83148fb9

